# Generated by Django 2.2 on 2020-09-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birthdate', models.DateField(null=True)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=255)),
                ('story_pic1', models.ImageField(upload_to='images/')),
                ('story_cap1', models.CharField(max_length=255)),
                ('story_pic2', models.ImageField(upload_to='images/')),
                ('story_cap2', models.CharField(max_length=255)),
                ('story_pic3', models.ImageField(upload_to='images/')),
                ('story_cap3', models.CharField(max_length=255)),
                ('desc', models.TextField(max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_created', to='whats_your_story_app.User')),
                ('users_who_like', models.ManyToManyField(related_name='liked_stories', to='whats_your_story_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_created', to='whats_your_story_app.User')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_comments', to='whats_your_story_app.Story')),
            ],
        ),
    ]
