# Generated by Django 2.2 on 2020-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_your_story_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_cap2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_cap3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
