# Generated by Django 2.2 on 2020-09-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whats_your_story_app', '0002_auto_20200914_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_cap1',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_cap2',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_cap3',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_pic1',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_pic2',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_pic3',
        ),
        migrations.AlterField(
            model_name='story',
            name='desc',
            field=models.TextField(max_length=2000),
        ),
        migrations.CreateModel(
            name='Story_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_pic', models.ImageField(upload_to='images/')),
                ('story_cap', models.CharField(max_length=255)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_images', to='whats_your_story_app.Story')),
            ],
        ),
    ]
